#!/usr/bin/env python3
"""
cns_audio.py

Fixed-source character pronunciation audio from CNS11643 / 全字庫
(human-recorded Taiwan Mandarin). There is NO synthesis here: the
resolver answers exactly one question — does the CNS index hold a
recording for (character, expected Zhuyin)?

Matching rules (never violated):
  - match key is (character, NORMALIZED expected Zhuyin);
  - expected Pinyin is secondary factual metadata only, never a key;
  - a missing reading returns unavailable: NO fallback to another
    reading, NO TTS, NO guessing. Wrong pronunciation is worse than
    missing pronunciation.

Official data contract (verified against the live official sources —
dataset page https://data.gov.tw/dataset/5961, listing
https://www.cns11643.gov.tw/opendata/OpenDataFilesList.csv,
release.txt, Properties.zip, MapingTables.zip, Voice.zip layout and
the in-archive voice readme; see download.py CNS11643_RESOURCES):
  - Properties.zip -> CNS_phonetic.txt: UTF-8-SIG, `<CNS-code>\\t<bopomofo>`
    per row (e.g. `1-4421\\tㄧˊ`); first tone UNMARKED (no ˉ anywhere in
    the file); neutral tone is a LEADING ˙ (e.g. `˙ㄇㄚ`); one row per
    reading, so polyphonic codes repeat.
  - MapingTables.zip -> Unicode/CNS2UNICODE_Unicode {BMP,2,3,15}.txt:
    UTF-8-SIG, `<CNS-code>\\t<HEX-Unicode>` per row.
  - Voice.zip -> male.zip / female.zip / 全字庫聲音檔說明文件.txt;
    nested archives hold `M_<hanpin>.mp3` (male) / `F_<hanpin>.mp3`
    (female) — underscore between prefix and hanpin, as extracted on
    disk (the readme prose omits the underscore). Neutral-tone clips
    (`<hanpin>5`, e.g. `M_a5.wav`) are `.wav`, not `.mp3`.
    The bopomofo->hanpin table (`bopomofo\\thanpin` rows) is
    parsed from the EXTRACTED official readme at index-build time —
    never hardcoded here.

The processed index (``data/processed/cns11643/cns_index.json``) is
generated BY THIS PROJECT via ``build_cns_index()`` from the resources
above. No manual sidecar is ever required.
"""

from __future__ import annotations

import hashlib
import json
import unicodedata
from dataclasses import asdict, dataclass, field
from pathlib import Path

CNS_SOURCE = "cns11643"
CNS_INDEX_VERSION = "cns-index-v2"
# Bumped v1 -> v2: filename construction fixed to the real on-disk layout
# (``{prefix}_{hanpin}`` with underscore + .wav fallback for neutral-tone
# clips). Old indexes built with the wrong layout are always empty.
CNS_PARSER_VERSION = "cns-parser-v2"

# Preferred-voice values accepted by the resolver. These select ONLY
# among human recordings already present in a CNS record; they are NOT
# model selection. Honored when records carry voice metadata, inert
# otherwise (deterministic fallback, documented in resolve()).
PREFERRED_VOICES = ("auto", "male", "female")

AUDIO_EXTS = {".wav", ".mp3", ".ogg", ".m4a"}

# Bopomofo tone marks used by CNS11643 (verified: no ˉ in
# CNS_phonetic.txt — first tone is unmarked).
_CNS_TONE_MARKS = "ˊˇˋ˙"
_BOPOMOFO_BODY = set(
    "ㄅㄆㄇㄈㄉㄊㄋㄌㄍㄎㄏㄐㄑㄒㄓㄔㄕㄖㄗㄘㄙ"
    "ㄚㄛㄜㄝㄞㄟㄠㄡㄢㄣㄤㄥㄦㄧㄨㄩ"
)


class CnsError(RuntimeError):
    """CNS audio misconfiguration / missing data / malformed index."""


def normalize_zhuyin(value: object) -> str:
    """Normalize a Zhuyin reading for exact index matching.

    Accepts both the pipeline form (explicit trailing ˉ for first tone)
    and the CNS form (first tone unmarked): a single trailing ˉ is
    stripped because CNS11643 never uses it (verified: zero occurrences
    in CNS_phonetic.txt). Neutral tone keeps its leading ˙, matching
    the CNS convention (`˙ㄇㄚ`).

    Returns "" when there is no usable single reading (empty, multiple
    whitespace-separated readings, or non-Bopomofo content). Callers
    treat "" as unavailable — never as a license to pick another clip.
    """
    text = unicodedata.normalize("NFC", str(value or "")).strip()
    if not text or any(ch.isspace() for ch in text):
        return ""
    token = text.replace("/", " ").split()
    if len(token) != 1:
        return ""
    token = token[0]
    if token.endswith("ˉ"):
        token = token[:-1]
    if not token:
        return ""
    if any(ch not in _BOPOMOFO_BODY and ch not in _CNS_TONE_MARKS
           for ch in token):
        return ""
    if not any(ch in _BOPOMOFO_BODY for ch in token):
        return ""
    return token


def zhuyin_slug(value: str) -> str:
    """Short deterministic ASCII slug of a normalized Zhuyin reading."""
    digest = hashlib.sha256(value.encode("utf-8")).hexdigest()[:8]
    return digest


@dataclass
class CnsRecord:
    """One CNS pronunciation recording (processed-index row)."""

    character: str = ""
    zhuyin_norm: str = ""
    zhuyin_src: str = ""
    record_id: str = ""
    voice: str = ""
    relpath: str = ""
    sha256: str = ""


@dataclass
class CharacterAudioResolver:
    """Deterministic (character, Zhuyin) -> CNS recording lookup.

    Built once per generation run via load(); resolve() is then a pure
    dict lookup (cheap enough for OFFICIAL full-dataset generation).
    """

    records: list = field(default_factory=list)
    index_version: str = ""
    record_count: int = 0
    _by_key: dict = field(default_factory=dict, repr=False)

    @classmethod
    def load(cls, index_path: Path | str) -> "CharacterAudioResolver":
        """Load a processed CNS index once. Raises CnsError when the
        dataset is absent or malformed (callers continue without audio)."""
        path = Path(index_path)
        if not path.exists():
            raise CnsError(
                f"CNS pronunciation index not found: {path}. "
                "Run `python download.py` to acquire CNS11643 resources "
                "(see download.py CNS11643_RESOURCES), then generate.py "
                "will attach audio. Cards generate without audio meanwhile."
            )
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, ValueError) as exc:
            raise CnsError(
                f"CNS pronunciation index unreadable: {path}: {exc}. "
                "Delete it and re-run `python download.py`, or generate "
                "without audio."
            ) from exc
        if not isinstance(data, dict) or data.get("index_version") != (
                CNS_INDEX_VERSION):
            raise CnsError(
                f"CNS pronunciation index has unsupported schema: {path} "
                f"(want index_version={CNS_INDEX_VERSION!r}). Delete it "
                "and re-run `python download.py`."
            )
        raw_records = data.get("records", [])
        if not isinstance(raw_records, list):
            raise CnsError(
                f"CNS pronunciation index records malformed: {path}.")
        records: list[CnsRecord] = []
        by_key: dict[tuple[str, str], list[CnsRecord]] = {}
        for row in raw_records:
            if not isinstance(row, dict):
                continue
            rec = CnsRecord(
                character=str(row.get("character", "") or ""),
                zhuyin_norm=str(row.get("zhuyin_norm", "") or ""),
                zhuyin_src=str(row.get("zhuyin_src", "") or ""),
                record_id=str(row.get("record_id", "") or ""),
                voice=str(row.get("voice", "") or ""),
                relpath=str(row.get("relpath", "") or ""),
                sha256=str(row.get("sha256", "") or ""),
            )
            if len(rec.character) != 1 or not rec.zhuyin_norm:
                continue
            records.append(rec)
            by_key.setdefault(
                (rec.character, rec.zhuyin_norm), []).append(rec)
        for key in by_key:
            by_key[key].sort(key=lambda r: (
                r.voice or "", r.record_id or "", r.relpath or ""))
        return cls(records=records, index_version=CNS_INDEX_VERSION,
                   record_count=len(records), _by_key=by_key)

    def resolve(self, character: str, expected_zhuyin: object,
                expected_pinyin: object = None,
                preferred_voice: str = "auto") -> tuple:
        """Resolve (character, expected Zhuyin) to a CNS record.

        Returns (record | None, info dict). ``info`` always echoes the
        normalized expected reading plus ``matched``/``reason``; the
        expected Pinyin travels as secondary metadata only.
        preferred_voice selects among same-reading recordings WHEN the
        records carry voice metadata, else deterministic first-sorted.
        """
        norm = normalize_zhuyin(expected_zhuyin)
        info: dict = {
            "matched": False,
            "expected_zhuyin": norm,
            "expected_pinyin": str(expected_pinyin or ""),
            "reason": "",
        }
        if len(character or "") != 1:
            info["reason"] = "not_single_character"
            return None, info
        if not norm:
            info["reason"] = "no_expected_reading"
            return None, info
        cands = self._by_key.get((character, norm), [])
        if not cands:
            info["reason"] = "reading_not_in_cns"
            return None, info
        pref = str(preferred_voice or "auto").strip().lower()
        if pref not in PREFERRED_VOICES:
            pref = "auto"
        chosen = cands[0]
        if pref != "auto":
            for rec in cands:
                if rec.voice.strip().lower() == pref:
                    chosen = rec
                    break
        info.update({
            "matched": True,
            "record_id": chosen.record_id,
            "matched_zhuyin": chosen.zhuyin_norm,
            "voice": chosen.voice,
            "relpath": chosen.relpath,
            "sha256": chosen.sha256,
            "candidates": len(cands),
        })
        return chosen, info


def sha256_file(path: Path, chunk_size: int = 1024 * 1024) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        while True:
            chunk = f.read(chunk_size)
            if not chunk:
                break
            h.update(chunk)
    return h.hexdigest()


def _read_text_file(path: Path) -> str:
    """Read an official CNS text resource (UTF-8-SIG verified)."""
    raw = path.read_bytes()
    for enc in ("utf-8-sig", "utf-8"):
        try:
            return raw.decode(enc)
        except UnicodeDecodeError:
            pass
    raise CnsError(f"cannot decode official CNS text file: {path}")


def parse_phonetic_table(text: str) -> list[tuple[str, str]]:
    """Parse CNS_phonetic.txt: `<CNS-code>\\\\t<bopomofo>` per row.

    Returns [(cns_code, bopomofo_src)] preserving file order. Blank
    lines are ignored; malformed rows raise CnsError.
    """
    rows: list[tuple[str, str]] = []
    for lineno, line in enumerate(text.splitlines(), start=1):
        if not line.strip():
            continue
        parts = line.split("\t")
        if len(parts) != 2 or not parts[0].strip() or (
                not parts[1].strip()):
            raise CnsError(
                f"CNS_phonetic.txt malformed row {lineno}: "
                f"{line[:60]!r}")
        rows.append((parts[0].strip(), parts[1].strip()))
    return rows


def parse_cns_mapping(text: str) -> dict[str, str]:
    """Parse CNS2UNICODE mapping files: `<CNS-code>\\\\t<HEX>` per row.

    Returns {cns_code: character}. Rows whose hex is not a valid code
    point raise CnsError (no silent drops of the join key space).
    """
    mapping: dict[str, str] = {}
    for lineno, line in enumerate(text.splitlines(), start=1):
        if not line.strip():
            continue
        parts = line.split("\t")
        if len(parts) != 2 or not parts[0].strip() or (
                not parts[1].strip()):
            raise CnsError(
                f"CNS mapping malformed row {lineno}: {line[:60]!r}")
        try:
            char = chr(int(parts[1].strip(), 16))
        except ValueError as exc:
            raise CnsError(
                f"CNS mapping bad code point row {lineno}: "
                f"{line[:60]!r}") from exc
        mapping[parts[0].strip()] = char
    return mapping


def parse_voice_readme_mapping(text: str) -> dict[str, str]:
    """Parse the official voice readme bopomofo->hanpin table.

    The readme documents `female.zip` = F + hanpin, `male.zip` =
    M + hanpin (mostly mp3 type), then a `bopomofo\\\\thanpin` table
    (e.g. `ㄒㄧㄣˊ\\\\txing2`, first tone unmarked, neutral `˙X\\\\tX5`).
    On disk the extracted members are `{M,F}_<hanpin>.mp3` (underscore),
    and neutral-tone `<hanpin>5` clips are `.wav`.
    Returns {bopomofo_src: hanpin}. Duplicate bopomofo keys raise
    CnsError (the official table must be unambiguous).
    """
    mapping: dict[str, str] = {}
    for line in text.splitlines():
        if line.count("\t") != 1:
            continue
        bopo, hanpin = line.split("\t")
        bopo, hanpin = bopo.strip(), hanpin.strip()
        if not bopo or not hanpin or " " in hanpin:
            continue
        if not all(ch in _BOPOMOFO_BODY or ch in _CNS_TONE_MARKS
                   for ch in bopo):
            continue
        if bopo in mapping and mapping[bopo] != hanpin:
            raise CnsError(
                f"voice readme maps {bopo!r} to both "
                f"{mapping[bopo]!r} and {hanpin!r}")
        mapping[bopo] = hanpin
    if not mapping:
        raise CnsError("voice readme has no bopomofo\\thanpin table")
    return mapping


def _find_voice_readme(voice_dir: Path) -> Path:
    """Locate the official voice readme under the extracted Voice tree.

    Matches the documented 全字庫聲音檔說明文件.txt by decoded name;
    falls back to any top-level .txt mentioning bopomofo+hanpin.
    Raises CnsError when absent (never silently substituted).
    """
    if not voice_dir.exists():
        raise CnsError(
            f"CNS voice directory missing: {voice_dir} "
            "(extract Voice.zip first)")
    for cand in sorted(voice_dir.glob("*.txt")):
        if "聲音檔說明" in cand.name:
            return cand
    for cand in sorted(voice_dir.rglob("*.txt")):
        try:
            if "bopomofo" in cand.read_text(
                    encoding="utf-8-sig")[:4000]:
                return cand
        except (OSError, ValueError):
            continue
    raise CnsError(
        f"official voice readme not found under {voice_dir}: want the "
        "全字庫聲音檔說明文件.txt shipped in Voice.zip")


def cns_index_inputs_hash(parts: dict[str, str]) -> str:
    """Hash of the source inputs an index build consumed."""
    canonical = json.dumps(parts, ensure_ascii=False, sort_keys=True)
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def cns_source_fingerprint(raw_dir: Path | str) -> dict | None:
    """Hash the current official CNS inputs WITHOUT building records.

    Returns {"inputs_hash": ..., "files": {...}} or None when any
    required input (phonetic table, mapping files, voice readme) is
    missing. download.py compares inputs_hash against the stored index
    to skip rebuilds when nothing changed.
    """
    raw = Path(raw_dir)
    phonetic_path = raw / "properties" / "CNS_phonetic.txt"
    mapping_dir = raw / "mapping"
    mapping_files = sorted(mapping_dir.rglob("CNS2UNICODE_*.txt")) \
        if mapping_dir.exists() else []
    if not phonetic_path.exists() or not mapping_files:
        return None
    try:
        readme_path = _find_voice_readme(raw / "audio")
    except CnsError:
        return None
    try:
        parts = {
            "phonetic": sha256_file(phonetic_path),
            "mapping": sha256_file(mapping_files[0])
            if len(mapping_files) == 1 else "+".join(
                sorted(sha256_file(p) for p in mapping_files)),
            "readme": sha256_file(readme_path),
            "parser": CNS_PARSER_VERSION,
        }
    except OSError:
        return None
    return {"inputs_hash": cns_index_inputs_hash(parts), "files": {
        "phonetic": phonetic_path.relative_to(raw).as_posix(),
        "mapping": [p.relative_to(raw).as_posix() for p in mapping_files],
        "readme": readme_path.relative_to(raw).as_posix(),
    }}


def build_cns_index(raw_dir: Path | str, out_path: Path | str,
                    *, audio_root: Path | str | None = None) -> dict:
    """Build the processed CNS lookup index from official originals.

    Consumes, all under ``raw_dir`` (data/raw/cns11643/):
      - properties/CNS_phonetic.txt .... code -> bopomofo rows
      - mapping/CNS2UNICODE_Unicode {BMP,2,3,15}.txt .. code -> char
      - audio/{male,female}/{M,F}_<hanpin>.mp3 (.wav for neutral-tone
        <hanpin>5 clips) + official voice readme
        (bopomofo -> hanpin filename table)

    For every (code, bopomofo): resolve the character via the mapping,
    normalize the Zhuyin, map bopomofo -> hanpin filename via the
    OFFICIAL readme table, and verify the member exists in BOTH voice
    dirs. Missing members are recorded in ``skipped`` (never indexed);
    unmapped CNS codes are recorded as ``unmapped``. Audio bytes are
    checksummed, never modified.

    ``audio_root`` overrides where relpaths resolve (tests); default is
    ``raw_dir`` so stored relpaths stay source-relative
    (``audio/female/F_xing2.mp3``).
    """
    raw = Path(raw_dir)
    out = Path(out_path)
    if not raw.exists():
        raise CnsError(f"CNS raw directory missing: {raw}")

    phonetic_path = raw / "properties" / "CNS_phonetic.txt"
    if not phonetic_path.exists():
        raise CnsError(
            f"official CNS_phonetic.txt not found: {phonetic_path} "
            "(fetch Properties.zip via `python download.py`)")
    mapping: dict[str, str] = {}
    mapping_files = sorted((raw / "mapping").rglob("CNS2UNICODE_*.txt")) \
        if (raw / "mapping").exists() else []
    if not mapping_files:
        raise CnsError(
            f"official CNS2UNICODE mapping files not found under "
            f"{raw / 'mapping'} (fetch MapingTables.zip via "
            "`python download.py`)")
    for path in mapping_files:
        mapping.update(parse_cns_mapping(_read_text_file(path)))

    voice_dir = raw / "audio"
    readme_path = _find_voice_readme(voice_dir)
    hanpin_of = parse_voice_readme_mapping(
        _read_text_file(readme_path))

    base = Path(audio_root) if audio_root is not None else raw
    inputs_hash = cns_index_inputs_hash({
        "phonetic": sha256_file(phonetic_path),
        "mapping": sha256_file(mapping_files[0])
        if len(mapping_files) == 1 else "+".join(
            sorted(sha256_file(p) for p in mapping_files)),
        "readme": sha256_file(readme_path),
        "parser": CNS_PARSER_VERSION,
    })

    records: list[dict] = []
    skipped: list[dict] = []
    unmapped: list[str] = []
    for code, bopo_src in parse_phonetic_table(
            _read_text_file(phonetic_path)):
        char = mapping.get(code)
        if char is None or len(char) != 1:
            if code not in unmapped:
                unmapped.append(code)
            continue
        znorm = normalize_zhuyin(bopo_src)
        if not znorm:
            skipped.append({"code": code, "reason": "bad_zhuyin",
                            "zhuyin": bopo_src})
            continue
        hanpin = hanpin_of.get(bopo_src)
        if hanpin is None:
            skipped.append({"code": code, "reason": "no_hanpin_mapping",
                            "zhuyin": bopo_src})
            continue
        for voice, prefix in (("male", "M"), ("female", "F")):
            # Real on-disk layout: `{prefix}_{hanpin}` with underscore
            # (the readme prose omits it). Neutral-tone `<hanpin>5`
            # clips ship as `.wav`, everything else as `.mp3`.
            audio_path = None
            for ext in (".mp3", ".wav"):
                cand = base / "audio" / voice / f"{prefix}_{hanpin}{ext}"
                if cand.exists():
                    audio_path = cand
                    break
            if audio_path is None:
                skipped.append({"code": code, "reason": "audio_missing",
                                "file": f"{prefix}_{hanpin}.mp3"})
                continue
            fn = audio_path.name
            records.append(asdict(CnsRecord(
                character=char,
                zhuyin_norm=znorm,
                zhuyin_src=unicodedata.normalize("NFC", bopo_src),
                record_id=code,
                voice=voice,
                relpath=audio_path.relative_to(base).as_posix()
                if _is_within(audio_path, base) else fn,
                sha256=sha256_file(audio_path),
            )))
    records.sort(key=lambda r: (
        r["character"], r["zhuyin_norm"], r["voice"] or "",
        r["record_id"] or "", r["relpath"] or ""))
    payload = {
        "index_version": CNS_INDEX_VERSION,
        "parser_version": CNS_PARSER_VERSION,
        "source": CNS_SOURCE,
        "inputs_hash": inputs_hash,
        "record_count": len(records),
        "records": records,
    }
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(payload, ensure_ascii=False, indent=2),
                   encoding="utf-8")
    return {"index": str(out), "records": len(records),
            "skipped": skipped, "unmapped": sorted(unmapped),
            "inputs_hash": inputs_hash}


def _is_within(path: Path, base: Path) -> bool:
    try:
        path.resolve().relative_to(base.resolve())
        return True
    except (OSError, ValueError):
        return False
